name: design
description: "A new Flutter package project."
version: 0.0.1
homepage:

environment:
  sdk: ^3.8.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  gap: ^3.0.1
  flutter_svg: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  assets:
    - assets/
    - assets/images/
    - assets/icons/
  fonts:
    - family: Nunito
      fonts:
        - asset: fonts/Nunito-ExtraLight.ttf
          weight: 200
        - asset: fonts/Nunito-ExtraLightItalic.ttf
          weight: 200
          style: italic
        - asset: fonts/Nunito-Light.ttf
          weight: 300
        - asset: fonts/Nunito-LightItalic.ttf
          weight: 300
          style: italic
        - asset: fonts/Nunito-Regular.ttf
          weight: 400
        - asset: fonts/Nunito-Italic.ttf
          weight: 400
          style: italic
        - asset: fonts/Nunito-Medium.ttf
          weight: 500
        - asset: fonts/Nunito-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: fonts/Nunito-SemiBold.ttf
          weight: 600
        - asset: fonts/Nunito-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: fonts/Nunito-Bold.ttf
          weight: 700
        - asset: fonts/Nunito-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: fonts/Nunito-ExtraBold.ttf
          weight: 800
        - asset: fonts/Nunito-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: fonts/Nunito-Black.ttf
          weight: 900
        - asset: fonts/Nunito-BlackItalic.ttf
          weight: 900
          style: italic
